avi_cloud_discovery_wait: 180

avi_config:
  cloud:
    - api_version: 18.1.3
      name: "{{ AviCloudName }}"
      vtype: CLOUD_VCENTER
      dhcp_enabled: false
      apic_mode: true
      apic_configuration:
        se_tunnel_mode: true
        apic_password: "{{ apic_password }}"
        apic_username: "{{ apic_username }}"
        context_aware: "SINGLE_CONTEXT"
        apic_admin_tenant: "common"
        apic_domain: "{{ apic_VMM }}"
        apic_name: 
          - "{{ apic_ip }}"
      license_type: "LIC_CORES"
      vcenter_configuration:
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "Apic"
        management_network: '/api/vimgrnwruntime?name={{ mgmt_network }}'
        privilege: "WRITE_ACCESS"
        vcenter_url: "{{ vcenter_ip }}"
        management_ip_subnet:
          ip_addr:
            addr: 10.128.3.0
            type: V4
          mask: 24
          static_ranges:
            - begin:
                addr: 10.128.3.10
                type: V4
              end:
                addr: 10.128.3.15
                type: V4


  

  serviceenginegroup:
    - name: Default-Group
      cloud_ref: '/api/cloud?name={{ AviCloudName }}'
      vcenter_folder: Stephane
      #vcenter_clusters:
      #  cluster_refs:
      #    - '/api/vimgrclusterruntime?name=Arista'
      #  include: True
      min_se: 2
      max_se: 4
      buffer_se: 0
