---

- hosts: localhost
  connection: local
  vars_files:
    - vars/creds.yml
    - vars/tenant_vars.yml
    
  roles:
    - role: avinetworks.avisdk
  tasks:
  
# Add static ranges for tenant networks (for SE address static allocation) 
    - name: Add static range for networks
      avi_network:
        api_version: "{{ api_version }}"
        avi_credentials: "{{ avi_credentials }}"
        name: "{{ Tenant }}:{{ item.bd }}"
        vrf_context_ref: '/api/vrfcontext/?name=global'
        tenant_ref: '/api/tenant/?name=admin' # 18.1.3 - ACI synced networks are in admin tenant 
        cloud_ref: "/api/cloud/?name={{ AviCloudName }}"
        configured_subnets:
          - prefix:
              ip_addr:
                type: V4
                addr: "{{ item.subnet }}"
              mask: "{{ item.subnet_mask }}"
            static_ranges:
            - begin:
                type: V4
                addr: "{{ item.start_addr }}"
              end:
                type: V4
                addr: "{{ item.end_addr }}"
        exclude_discovered_subnets: false
        dhcp_enabled: false
        #vcenter_dvs: true
      loop:
        - { bd: "{{ bd_1 }}", subnet: "{{ bd_1_subnet }}", subnet_mask: "{{ bd_1_subnet_mask }}", start_addr: "{{ bd_1_subnet_start_addr }}", end_addr: "{{ bd_1_subnet_end_addr }}" }
        - { bd: "{{ bd_2 }}", subnet: "{{ bd_2_subnet }}", subnet_mask: "{{ bd_2_subnet_mask }}", start_addr: "{{ bd_2_subnet_start_addr }}", end_addr: "{{ bd_2_subnet_end_addr }}" }
       
