# use api_session module to get cluster uuid and extract Avi Cluster Name used for APIC registration
#
---

- hosts: localhost
  connection: local
  vars_files:
    - vars/creds.yml
        
  roles:
    - role: avinetworks.avisdk

  tasks:
    - name: get Avi cluster info from api
      avi_api_session:
        avi_credentials: "{{ avi_credentials }}"
        http_method: get
        path: cluster
      register: cluster_infos
    
    - name: display Avi cluster uuid
      debug: msg="{{ cluster_infos.obj.uuid }}"
     
    - set_fact: # use jinja2 filter to extract id chunks
        cluster1: "{{ cluster_infos.obj.uuid.split('-')[1] }}"
        cluster2: "{{ cluster_infos.obj.uuid.split('-')[2] }}"
        
    - set_fact: # Avi Cluster Name used for APIC registration
        avi_device: "Avi_{{ cluster1 }}_{{ cluster2 }}"

    - name: display extracted clustername
      debug: msg="Here is the Cluster Name used for ACI registration {{ avi_device }}"

- hosts: apic
  connection: local
  vars_files:
    - vars/apic_vars.yml
    - vars/tenant_vars.yml
  
  tasks:
    - name: get L4-L7 Avi device info
      aci_rest:
        host: "{{ apic_host }}"
        username: "{{ apic_username }}"
        password: "{{ apic_password }}"
        use_proxy: "{{ apic_use_proxy }}"
        use_ssl: "{{ apic_use_ssl }}"
        validate_certs: "{{ apic_validate_certs }}"
        method: get
        path: /api/node/mo/uni/tn-common/lDevVip-{{ hostvars['localhost']['avi_clustername'] }}.json

    - name: export from common to target tenant
      aci_rest:
        host: "{{ apic_host }}"
        username: "{{ apic_username }}"
        password: "{{ apic_password }}"
        use_proxy: "{{ apic_use_proxy }}"
        use_ssl: "{{ apic_use_ssl }}"
        validate_certs: "{{ apic_validate_certs }}"
        method: post
        path: /api/node/mo/uni/tn-common/lDevVip-{{ hostvars['localhost']['avi_clustername'] }}.json
        content: {"vnsLDevIf":{"attributes":{"dn":"uni/tn-{{ Tenant }}/lDevIf-[uni/tn-common/lDevVip-{{ hostvars['localhost']['avi_clustername'] }}]","ldev":"uni/tn-common/{{ hostvars['localhost']['avi_clustername'] }}","status":"created,modified","rn":"lDevIf-[uni/tn-common/lDevVip-{{ hostvars['localhost']['avi_clustername'] }}]"},"children":[]}}

# export not tested